# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14edad72a60831a1f78f3939f5d7f563d1096e7d80a796e7bf6ba15e313885315df0fb6d5bb5b2b230cc041477efe0c142c674f004b41eb29fd5810730141fe6

test:
  secret_key_base: 9a8ff3ca89bb384f066a9e9835055af65c388e09937cd4210ac319a513dbf4f0a835fdff111263334aabb30cdb3c73a1176ebeaf04afe897bfd0d3e5bca1db89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
